config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations'}
  root 'welcome#index'

  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map{ |name, i| ["#{i+1} - #{name}", i+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create email: email, source: token
    Stripe::Charge.create customer: customer.id,
                          amount: 1000,
                          description: 'Premium',
                          currency: 'usd'
  
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :payment
  accepts_nested_attributes_for :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def create
    build_resource(sign_up_params)

    resource.class.transaction do 
      resource.save
      yield resource if block_given?

      if resource.persisted?
        @payment = Payment.new({email: params["user"]["email"],
          token: params[:payment]["token"], user_id: resource.id})
        flash[:error] = "Please check  registration errors" unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message

          resource.destroy
          puts 'Payment failed'
          render :new and return        
        end
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end   
    end
  end
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/stripe_checkout_standard_payment_form.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
  <span>Amount: $<%= @order.price %></span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="<%= @order.price %>"
  data-locale="auto"></script>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">PhotoApp</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-right col-md-4">
        <% if current_user %>
        <li class="col-md-8 user-name">
          <%= link_to "Edit profile", edit_user_registration_path, class: "fa fa-user" %>
        </li>
        <li class="col-md-1"> </li>
        <li class="col-md-3 logout">
          <%= link_to "Log Out", destroy_user_session_path, class: 'btn btn-xs btn-danger', method: :delete  %>
        </li>
        <% else %>
        <li class="col-md-4 pull-right">
        <%= link_to "Log In", new_user_session_path, class: "btn btn-primary"%></li>
        <li class="col-md-4 "><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "http://js.stripe.com/v2/" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <footer>
          <p>&copy; PhotoMania 2020, Photo by Simon Wilkes on Unsplash</p>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  <h3>Welcome: <%= current_user.email %></h3>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      You'll love managing your Photos with our application. Sign up!
    </p>
  </div>

  <div class="row">
    <div class="plans clearfix">
      <div class="col-lg-3 col-lg-offset-3 plan">
        <h2>Premium Plan</h2>
        <div class="price pull-right">
          Price: $10
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
      <div class="col-lg-3 plan">
        <h2>Amaze Plan</h2>
        <div class="price pull-right">
          Price: $20
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
            <li class='extra'>Unlimited projects</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
    </div>
  </div>
<% end %>